### ISSUE TITLE
Add method for loading images from URL.

### ISSUE THREAD

**Issue by VEINHORN** [VEINHORN/ScrollGalleryView#11]

**Comment by rajasharan** [comment]
Hi - are you already working on this? If not can I work on it. 

I've an idea: use some kind of HandlerThread to load images and sendMessage to main thread.

**Comment by VEINHORN** [comment]
@rajasharan Hi. I haven't worked on it yet. Good idea, but i would like to add image caching in the future. What do you think about using Fresco, Glide or Picasso for this purposes?

**Comment by rajasharan** [comment]
@VEINHORN hmm - I've never used any of those to be honest. I'll research more in the coming days.

**Comment by alexodus** [comment]
+1

**Comment by inver** [comment]
@rajasharan @alexodus 
Hi guys! I improved library for loading image from urls. You can check this in my fork.
