### ISSUE TITLE
How to make library to work without FragmentActivity?

### ISSUE THREAD

**Issue by lovesuper** [VEINHORN/ScrollGalleryView#17]
I faced with vexing problem. Your library doesn't work with "new style coding" - without using FragmentActivity as a parent class for main activity. How can I make your code work?

**Comment by VEINHORN** [comment]
@lovesuper Hello! This library uses FragmentManager, so you need to extend activity such as FragmentActivity. I'm working on it now.

**Comment by VEINHORN** [comment]
AppCompatActivity

**Comment by VEINHORN** [comment]
For now the library is heavily based on FragmentActivity, so you need to extend your activity from FragmentActivity or other activities that's extended from FragmentActivity such as AppCompatActivity.
