### ISSUE TITLE
ImageView no longer exists

### ISSUE THREAD

**Issue by VEINHORN** [VEINHORN/ScrollGalleryView#28]
03-15 21:21:41.280 23678-23678/com.veinhorn.scrollgalleryview I/PhotoViewAttacher: ImageView no longer exists. You should not use this PhotoViewAttacher any more.

**Comment by wurstnudl** [comment]
I'm using the same attacher too.

Calling photoViewAttacher.cleanup() in the appropriate place should probably help you.
