### ISSUE TITLE
Can i add text for each imageview

### ISSUE THREAD

**Issue by firestork** [VEINHORN/ScrollGalleryView#30]
Can i add text for each imageview

**Comment by VEINHORN** [comment]
@firestork For now not. I plan to add it in next release.

**Comment by firestork** [comment]
Thanks you.

**Comment by lesjaw** [comment]
Is it already added? How to add text in image?

**Comment by andreluizreis** [comment]
I look forward to this feature too.

**Comment by UniqueJoy** [comment]
does it added in the current release @VEINHORN ???

**Comment by VEINHORN** [comment]
@UniqueJoy Hi! At the current moment, i mean version `1.2.6` this feature is unsupported. :/ But you can change text in *ActionBar* [like this](https://github.com/VEINHORN/ScrollGalleryView/issues/65#issuecomment-373049065) (using *ScrollGalleryView* callbacks). But I'm working on this feature and I hope it will appear in next release.

**Comment by VEINHORN** [comment]
@firestork @lesjaw @andreluizreis @UniqueJoy Starting from version `1.2.7` you can now add images with description using `MediaInfo image(String url, String description);` method from *MediaHelper* interface:

```java
.add(image(
                        "https://i.pinimg.com/originals/1b/d3/f0/1bd3f0e146da86f9c504e89a0b7e1403.jpg",
                        "Old Ship"
                ))
```

 or directly to the *ScrollGalleryView* using `addMedia()` method:

```java
galleryView.addMedia(MediaInfo.mediaLoader(
                        new PicassoImageLoader("https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/USRC_Salmon_P_Chase_-_LoC_4a25817u.jpg/1200px-USRC_Salmon_P_Chase_-_LoC_4a25817u.jpg"),
                        "The word barque entered English via French, which in turn came from the Latin barca by way of Occitan, Catalan, Spanish or Italian."
                ));
```

So now text on each image looks like this:

![screenshot](https://previews.dropbox.com/p/thumb/AAVfZBX7J_L5lz4GzgEXwWcW5PjhfdfeLmCaKU-nrBpjOBpocBWzpHiznEEnVjZpGkUP_9hcXbzqrZbBkjPvkka2PgcPkUTTB8gq8tzXnamfC1j8yQo_tVCmD4pjyuw-lJmPX_Wz3wdqNl0uAQN5r1ynr0UAEBFJd9O8AbJNCQ6WJEgQTO3yTtFA1E2YFH_XO4QwlT76j7PYIDaYsoiRM9bZhqtoYGg034sLWDWXf_6q5A/p.png)
