### ISSUE TITLE
Ability to remove images / clear gallery

### ISSUE THREAD

**Issue by seliv** [VEINHORN/ScrollGalleryView#33]
It would be nice to have a method for resetting gallery to its initial state (empty gallery - no images added). This would allow reusing the same gallery instance to show various sets of images.

My use case: I have a social network client app that shows a feed of posts. Each post may have its own collection of attached images. I want to reuse a single overlayed gallery instance to show images, and refill it with a list of images from different posts.

**Comment by VEINHORN** [comment]
Starting from `1.0.8` you can use `clearGallery()` method to clean all images from gallery.

### Dependency

```
compile 'com.veinhorn.scrollgalleryview:library:1.0.8'
```

**Comment by Ahsan221B** [comment]
Hi @VEINHORN! The `clearGallery()` method is not working. I am using the following dependencies:
`    implementation 'com.veinhorn.scrollgalleryview:library:1.2.8'
    implementation 'com.veinhorn.scrollgalleryview:picasso-loader:1.2.8'
`
It would be a great help if you can provide some assistance here. I need to deliver a project in the next 2 hours. Thank you!
