### ISSUE TITLE
Request to publish 1.0.6 to jcenter

### ISSUE THREAD

**Issue by MythicAngel** [VEINHORN/ScrollGalleryView#40]
As specificed [here](https://github.com/PALADIN-AC/Android-Wallpaperify/issues/1) , latest codes are not available in jcenter and I cannot use viewpager. Please publish latest codes to jcenter for **1.0.6** version.

**Comment by WesPoon** [comment]
same request as above

**Comment by javiersuazo** [comment]
You can always use jitpack to get the last version of the repo into your app. Just in case it helps. :)

**Comment by VEINHORN** [comment]
For now the `getViewPager()` method is available in `1.0.6` and higher.
