### ISSUE TITLE
SetCurrentItem doesn't set it for the thumbnails

### ISSUE THREAD

**Issue by haideralipunjabi** [VEINHORN/ScrollGalleryView#43]

**Comment by voghDev** [comment]
Also, `.setCurrentItem` crashes when called in the Builder. Like this:

     scrollGalleryView
                .setThumbnailSize(100)
                .setZoom(true)
                .setCurrentItem(1)
                .setFragmentManager(getSupportFragmentManager())
                .addMedia(infos);

**Comment by VEINHORN** [comment]
@voghDev I will try fix that bug in the next version.

**Comment by mngzir** [comment]
> @voghDev I will try fix that bug in the next version.

Thumbnail position not change

**Comment by YashMundra2411** [comment]
Did you find anything for setting thumbnail position?
