### ISSUE TITLE
Only 5 images

### ISSUE THREAD

**Issue by Santipu** [VEINHORN/ScrollGalleryView#50]
Hi

I have got a problem. IN android version 4.2.2 the app run great.
In a new dispositive with version 4.4.4., the same code only show 5 images.
Can you help me please?

**Comment by VEINHORN** [comment]
@Santipu I can recommend you to use custom [MediaLoader](https://github.com/VEINHORN/ScrollGalleryView/blob/master/library/src/main/java/com/veinhorn/scrollgalleryview/loader/MediaLoader.java) which helps to eliminate a bunch of problems with image loading and caching. You can try [picasso-loader](https://github.com/VEINHORN/ScrollGalleryView/tree/master/picasso-loader) which is available for now. I'm going to add more implementations soon.
