### ISSUE TITLE
TransactionTooLargeException on Nougat

### ISSUE THREAD

**Issue by agaDeonix** [VEINHORN/ScrollGalleryView#52]
When open images and collapse app, show error. This maybe in ImageFragment in onSaveInstanceState method when call
outState.putParcelable("image", ((BitmapDrawable)this.backgroundImage.getDrawable()).getBitmap());

**Comment by stefanopassador** [comment]
Same here!
This problem crushes the app.

**Comment by mengoni** [comment]
same problem here, it crashes turning off the screen

**Comment by VEINHORN** [comment]
@stefanopassador Hi. Can you please provide a pull request?
