### ISSUE TITLE
Remove app name from library resources

### ISSUE THREAD

**Issue by trupizzza** [VEINHORN/ScrollGalleryView#58]
I think it's better to remove resources such as app_name from the library, because it can cause clashes with app's own app_name resource.
If someone uses app_name resource value (especially in layout, which was in my case), he will see ScrollGalleryView instead of his own app name.

_Library has two res files which contains app_name string:_
**ScrollGalleryView/library/src/main/res/values-ru/strings.xml**
**ScrollGalleryView/library/src/main/res/values/strings.xml**

**Comment by VEINHORN** [comment]
Hi @trupizzza . Thank you for the nice idea. 👍 Can you please create a pull request if you have some free time?

**Comment by trupizzza** [comment]
@VEINHORN  Of course! 
Btw, there are many users encountered a problem with memory overflow using Picasso or Glide - discovering that problem now. 
I'll let you know if I solve it - I have some thoughts about these errors in terms of Glide, Piccasso could be fixed in the same way
