### ISSUE TITLE
Provide image loaders as separate modules

### ISSUE THREAD

**Issue by VEINHORN** [VEINHORN/ScrollGalleryView#61]
Provide image loaders for most popular downloading and caching libraries as separate modules (dependencies).

- [x] Picasso
- [ ] Glide
- [ ] Fresco

**Comment by Oziomajnr** [comment]
Looks like the check list is complete... this issue can be closed right?

**Comment by VEINHORN** [comment]
@Oziomajnr Hi! We also need to update README (add instructions how to fetch loaders from repository, maybe JitPack for now). When this will be done I'll close issue.

**Comment by VEINHORN** [comment]
Published MediaLoaders implementations for Picasso, Glide, Fresco libraries to JCenter. Added some notes to README.
