### ISSUE TITLE
How to use on Fragment?

### ISSUE THREAD

**Issue by WrathChaos** [VEINHORN/ScrollGalleryView#64]
Hello,
I really love your library, but I could not use it on Fragment. Is there a way to use it on Fragment?
Thank you, 
Have fun :)

**Comment by VEINHORN** [comment]
@WrathChaos hi. :) Thank you for the kind words.
**ScrollGalleryView** is implemented on top of a ViewPager which uses FragmentActivity with separate Fragment for each image. So for now the gallery doesn't support viewing images in a single Fragment. I've already though about this but it would require a lot of effort to implement and there are a bunch of other features which I want to implement in next versions.

**Comment by WrathChaos** [comment]
@VEINHORN I hope you will develop these features soon, totally the best gallery on the market :) Let's boost it. Thank you for reply :)
