### ISSUE TITLE
How can i add Text per image

### ISSUE THREAD

**Issue by tellfa** [VEINHORN/ScrollGalleryView#65]
How can i add textview for show image numbers ?

**Comment by VEINHORN** [comment]
@tellfa hi. This feature is unsupported for now, but you can show image numbers in ActionBar (using `addOnImageClickListener()`). Something like **1 of 10**.

**Comment by VEINHORN** [comment]
@tellfa Starting from version `1.2.7` you can add text per image. See details [here](https://github.com/VEINHORN/ScrollGalleryView/issues/30#issuecomment-462142877).
