### ISSUE TITLE
PicassoImageLoader class not found

### ISSUE THREAD

**Issue by nyumaiku** [VEINHORN/ScrollGalleryView#66]
PicassoImageLoader not added with dependency

**Comment by iceboy1369** [comment]
import android.content.Context;
import android.widget.ImageView;

import com.squareup.picasso.Callback;
import com.squareup.picasso.Picasso;
import com.veinhorn.scrollgalleryview.loader.MediaLoader;

public class PicassoImageLoader implements MediaLoader {
    private String url;
    private Integer thumbnailWidth;
    private Integer thumbnailHeight;

    public PicassoImageLoader(String url) {
        this.url = url;
    }

    public PicassoImageLoader(String url, Integer thumbnailWidth, Integer thumbnailHeight) {
        this.url = url;
        this.thumbnailWidth = thumbnailWidth;
        this.thumbnailHeight = thumbnailHeight;
    }

    @Override
    public boolean isImage() {
        return true;
    }

    @Override
    public void loadMedia(Context context, final ImageView imageView, final MediaLoader.SuccessCallback callback) {
        Picasso.with(context)
                .load(url)
                .placeholder(R.drawable.noimage2)
                .into(imageView, new ImageCallback(callback));
    }

    @Override
    public void loadThumbnail(Context context, final ImageView thumbnailView, final MediaLoader.SuccessCallback callback) {
        Picasso.with(context)
                .load(url)
                .resize(thumbnailWidth == null ? 100 : thumbnailWidth,
                        thumbnailHeight == null ? 100 : thumbnailHeight)
                .placeholder(R.drawable.placeholder_image)
                .centerInside()
                .into(thumbnailView, new ImageCallback(callback));
    }

    private static class ImageCallback implements Callback {
        private final MediaLoader.SuccessCallback callback;

        public ImageCallback(SuccessCallback callback) {
            this.callback = callback;
        }

        @Override
        public void onSuccess() {
            callback.onSuccess();
        }

        @Override
        public void onError() {

        }
    }
}

**Comment by VEINHORN** [comment]
As @iceboy1369 has mentioned you can manually copy the code of [PicassoImageLoader](https://github.com/VEINHORN/ScrollGalleryView/blob/master/picasso-loader/src/main/java/com/veinhorn/scrollgalleryview/loader/picasso/PicassoImageLoader.java) which can be found in [picasso-loader](https://github.com/VEINHORN/ScrollGalleryView/tree/master/picasso-loader) module. I`ll try to provide the separate dependency in several days cause I have some troubles with publishing using [gradle-bintray-plugin](https://github.com/bintray/gradle-bintray-plugin).

**Comment by VEINHORN** [comment]
For now it's available [as separate dependency](https://github.com/VEINHORN/ScrollGalleryView#picasso).
