### ISSUE TITLE
Image fails to re-load after rotate

### ISSUE THREAD

**Issue by StainlessStlRat** [VEINHORN/ScrollGalleryView#69]
Seems the mediaLoader callback is never called, but the one on the thumbs is.

End result is after rotation the thumbs are fine but the full images just remain place-holded.

**Comment by StainlessStlRat** [comment]
Anybody care anymore?

**Comment by ronanlima** [comment]
I have the same problem here

**Comment by StainlessStlRat** [comment]
Any chance to fix? Seems like it would be simple enough. Im currently locking the orientation when it’s visible, which is kinda hokey.

**Comment by VEINHORN** [comment]
@StainlessStlRat @ronanlima fixed in `1.2.5` version.

**Comment by StainlessStlRat** [comment]
Awesome! Thank you!!
