### ISSUE TITLE
Load a video

### ISSUE THREAD

**Issue by choungchamnab** [VEINHORN/ScrollGalleryView#81]
How to load video along with other images ? There is sample code but it not working.

**Comment by VEINHORN** [comment]
Hi @choungchamnab . Do you use one of provided loaders: `picasso-loader`, `glide-loader` or `fresco-loader`? If so you can try [this code](https://github.com/VEINHORN/ScrollGalleryView/blob/dev/docs/init-gallery.md#usage) or if you want to add video to already initialized gallery you may want to use [this one](https://github.com/VEINHORN/ScrollGalleryView/blob/dev/docs/init-gallery.md#usage-1).

**Comment by choungchamnab** [comment]
Thank you very much. Let me try .
